{
    "host": "51.159.169.225:13880", #айпи:порт
    "bots": 5, #скок ботов
    "enterrange": 6500, #задержка между соединениями (в милисекундах)
    "useproxy": false,
    "proxytype": "socks5", #socks4 socks5 http
    "KeepAlivePackets": false, #не советую менять
    "reconect": false,

    "visualizePath": false,
    "removeafter": true,

    "listenEntities": false,

    "raznos": false,

    #-------raid---------
    "raidmode": true, #режим рейд-атаки на сервер
    #---setup---
    "raidwalkradius": 3, #боты ходят на случайные координаты в этом радиусе относительно своих
    "walkeverymilseconds": 0, #цикл ходьбы каждые X милисекунд
    "withmining": true,
    "minertargetid": [9,8,498], #8 grass 16 sp log 47-oakwood 28-sand 452-oak_slab 13-oak_planks 9-dirt 1-stone 498-grass_path
    "raidspam": false, #спам в режиме рейда
    "spamrange": 1000, #спам каждые X милисекунд
    "timebeforeraidon": 500 #задержка между входом бота на сервер и включением режима рейд-атаки
    #-------raid---------
}
