{
    "host": "localhost:25565", #айпи:порт
    "bots": 1, #скок ботов
    "enterrange": 10, #задержка между соединениями (в милисекундах)
    "useproxy": false,
    "proxytype": "socks5", #socks4 socks5 http
    "KeepAlivePackets": false, #не советую менять
    "tickmode": true, #true - передача координат каждые 50 мс (не передаются если совпадают с предыдущими) | false - передача координат при каждом изменении
    "reconect": true,

    "visualizePath": true,
    "removeafter": true,

    "listenEntities": true,

    #-------raid---------
    "raidmode": false, #режим рейд-атаки на сервер
    #---setup---
    "raidwalkradius": 2, #боты ходят на случайные координаты в этом радиусе относительно своих
    "walkeverymilseconds": 3000, #цикл ходьбы каждые X милисекунд
    "raidspam": true, #спам в режиме рейда
    "spamrange": 1000, #спам каждые X милисекунд
    "timebeforeraidon": 2000 #задержка между входом бота на сервер и включением режима рейд-атаки
    #-------raid---------
}
