{
    "mode": 1, #1-рейд конеретного айпи 2-рейд всего мониторинга
    #-------------------------------mode-2---------------------------
    #"etime": 30, #сколько секунд занимает рейд сервера
    #"multipileraids": 2, #сколько серверов может рейдиться одновременно
    #-------------------------------mode-1---------------------------
    "host": "Gamesub10.aternos.me:12584", #айпи:порт
    #--------------------------general-settings----------------------
    "bots": -1, #скок ботов (если -1 то ботов будет столько же сколько проксей)
    "enterrange": 30, #задержка между соединениями (в милисекундах)
    "useproxy": true, #юзать прокси?
    "proxytype": "socks5", #socks4 socks5 http
    "KeepAlivePackets": false, #устарело + хуйня + не трогать
    "reconect": true, #при вылете с сервера боты перезаходят
    "multiworld": true, #обьедененный мир для всех ботов (лучше не трогать)
    "catchreg": true, #если true то боты при заходе на сервер не будут писать команды регистрации сразу а только если в чате будет уведомление о том что это надо написать
    "removeifnonactive": 0, #удаление ботов если они не могут подключиться с x попытки. 0 - не удалять

    "visualizePath": false, #хуйня

    "listenEntities": true, #не трогать

    "nuker": false, #нюкер, работает криво и только если у ботов креатив

    "isitfollow": false, #боты будут ходить около указаной цели
    "followtarget": "__Flashback__", #цель либо корды в формате (x z) (x y z) либо ник либо текст который копируется при нажатии f3+c (вставлять без изменений)
    "radius": 8, #радиус допустимый до позиции
    "displaymaps": true, #когда у бота в инвентаре появляется карта(капча), открывается окно с полем для ввода

    "pvpwithplayers": true, #включение режима пвп
    "pvpamongthemselves": false, #пвп среди ботов
    "pvpblacklist": ["__Flashback__"], #кого не будет трогать бот при пвп

    "window": false, #устарело
    "living": true, #по дефолту бот работает или стоит. изменяется в процессе игры командой >>living

    "loginfrase": "", #Что бот пишет после регистрации. Каждое сообщение разделяй знаком "|". Можно ваще ничо не писать.

    "chetodelat": false, # устарело
    "mineonlyiftouchair": true, #добывать блок только если вокруг него есть хоть 1 пустой блок
    "walkeverymilseconds": 0, #задержка между действиями
    "iol": false, #задает используемый список для копания. true - "minertargetid", false - "minetargetnames"
    "minertargetid": [8,35,13,12,139,191,243,146,498,452], #список айди блоков которые будет копать бот
    "minetargetnames": ["log","plank","quartz","stair","path","trapdoor","glass","chest","pot","fence",
    "door","sign","wool","smooth","bricks","table","furnace","bed","snow","cobble","barrel","fire","slab",
    "cutter","anvil","torch","wheat","stem","grass","dirt"], #список названий(можно не полным словом) блоков которые будет копать бот
    "maxpostoblock": 5, #дальность курсора бота
    "raidspam": true, #спам
    "spamrange": 1000, #задержка спама в милисекундах
    "timebeforeraidon": 2000 #задержка между входом бота на сервер и включением режима рейд-атаки
}
